trigger:
  - demo

pool:
  vmImage: 'ubuntu-latest'

pr: none

stages:
        
- stage: Functional_check 
  displayName: Functional_check 
  jobs:  
  - job: Functional_check
    displayName: Functional_check
    steps:        
    - task: NodeTool@0
      inputs:
        versionSpec: '18.17.1'
      displayName: 'Install Node.js'

    - script: |
          npm install
          npm run test
      displayName: 'Excuting Test Cases'
      
    - task: PublishCodeCoverageResults@2
      inputs:
        summaryFileLocation: 'coverage/clover.xml'
      displayName: 'Publish Code Coverage'



- stage: DEPLOY 
  displayName: DEPLOY 
  jobs:  
  - job: Deploy
    displayName: Deploy
    steps:
    
    - task: NodeTool@0
      inputs:
        versionSpec: '18.17.1'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Build App'
    
    - task: AzureStaticWebApp@0
      inputs:
        app_location: '/build'
        skip_app_build: true
        skip_api_build: true
        azure_static_web_apps_api_token: '$(STATIC_WEB_APP_TOKEN)'
      env:
        REACT_APP_BASE_URL: $(REACT_APP_BASE_URL)
        REACT_APP_EN_KEY: $(REACT_APP_EN_KEY)
        REACT_APP_GOOGLE_API_KEY: $(REACT_APP_GOOGLE_API_KEY)
        REACT_APP_BASE_URL_ASSET: $(REACT_APP_BASE_URL_ASSET)
        REACT_APP_BASE_URL_ASSET_TOKEN: $(REACT_APP_BASE_URL_ASSET_TOKEN)
        REACT_APP_DUMMY_EMAIL: $(REACT_APP_DUMMY_EMAIL)
        REACT_APP_DUMMY_PASSWORD: $(REACT_APP_DUMMY_PASSWORD)
        REACT_APP_PROGRESS_TIME: $(REACT_APP_PROGRESS_TIME)
        REACT_APP_BASE_URL_CA: $(REACT_APP_BASE_URL_CA)
        
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure Service Manager Endpoint'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az cdn endpoint purge --resource-group GREENSIGHT-DEMO-FRONTEND --profile-name GS-cdn-demo-global-001 --name gsdemocdnendpoint003 --content-paths "/*"' 
