trigger:
  - develop

pr: none

pool:
  vmImage: 'ubuntu-latest'

# variables:
#   - name: PROJECT_VERSION
#     value: "1.0.0"

stages:

# ---------- SECRETS ----------
- stage: Secrets
  displayName: "Read Secrets from Key Vault"
  jobs:
  - job: ReadSecrets
    displayName: "Key Vault Secrets"
    steps:
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'devops-secrect-reader'
          KeyVaultName: 'gs-keyvault-demo'
          SecretsFilter: '*'
          RunAsPreJob: true

# # ---------- QUALITY + SONAR ----------
# - stage: Quality
#   displayName: "Quality & Sonar"
#   dependsOn: Secrets
#   jobs:
#     - template: templates/test-cases.yml
#       parameters:
#         sonarenabled: true

# ---------- BUILD & DEPLOY ----------
- stage: Build_and_Deploy
  displayName: "Build & Deploy"
 # dependsOn: Quality
  jobs:
    - template: templates/static_web_app_deploy.yml
