trigger:
  - develop

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  # ACR_NAME: gsacrregistorydeveastus001 
  # ACR_REPOSITORY: gs-backend-dev-001
  # API_VERSION: 1.0.$(Build.BuildId)

stages:

# =========================================================
# QUALITY  
# =========================================================
# - stage: Quality
#   displayName: "Quality + Sonar"
#   jobs:
#     - template: templates/test_cases.yml

# # =========================================================
# # BUILD & PUSH  
# # =========================================================
- stage: Build_And_Push
  displayName: "Build & Push Image"
  dependsOn: Quality
  jobs:
    - template: templates/docker_build_and_push.yml
      parameters:
        acrname: $(ACR_NAME)
        acrrepository: $(ACR_REPOSITORY)
        apiversion: $(API_VERSION)
      


# # =========================================================
# # TRIVY SCAN  
# # =========================================================
# - stage: Trivy_Scan
#   displayName: "Security Scan (Trivy)"
#   dependsOn: Build_And_Push
#   jobs:
#     - template: templates/trivy.yml
#       parameters:
#         acrname: $(ACR_NAME)
#         acrrepository: $(ACR_REPOSITORY)
#         apiversion: $(API_VERSION)


# =========================================================
# DEPLOY 
# =========================================================
- stage: Deploy
  displayName: "Deploy to Dev"
  dependsOn: Trivy_Scan
  jobs:
    - template: templates/container_app_deploy.yml
      parameters:
        acrname: $(ACR-NAME)
        image: "$(ACR-NAME).azurecr.io/$(ACR-REPOSITORY):$(API-VERSION)"
        containerapp: $(CONTAINER-APP-NAME)
        rgname: $(RG-NAME)


# =========================================================
# POST DEPLOY  
# =========================================================
# - stage: PostDeploy
#   displayName: "Post Deployment Tasks"
#   dependsOn: Deploy
#   jobs:
#     - job: PostDeploy
#       displayName: "Run APIM updates"
#       steps:
#         - script: echo "Post-Deployment started..."
#           displayName: "Initialization step"

#         - task: AzureCLI@2
#           displayName: "Run APIM updates"
#           inputs:
#             azureSubscription: Azure Service Manager Endpoint
#             scriptType: bash
#             scriptLocation: inlineScript
#             inlineScript: |
#               sleep 30
#               $(APIMUPDATES)
