trigger:
  - research

pool:
  vmImage: 'ubuntu-latest'

pr: none

stages:
        
- stage: TEST 
  displayName: TEST 
  jobs:  
  - job: Test
    displayName: Test
    steps:        
    - script: |
         npm install 
         npm run test

- stage: DEPLOY 
  displayName: DEPLOY 
  jobs:  
  - job: Deploy
    displayName: Deploy
    steps:
    
    - task: NodeTool@0
      inputs:
        versionSpec: '18.17.1'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Build App'
    
    - task: AzureStaticWebApp@0
      inputs:
        app_location: '/build'
        skip_app_build: true
        skip_api_build: true
        azure_static_web_apps_api_token: '$(STATIC_WEB_APP_TOKEN)'
      env:
        REACT_APP_BASE_URL: $(REACT_APP_BASE_URL)
        REACT_APP_EN_KEY: $(REACT_APP_EN_KEY)
        REACT_APP_GOOGLE_API_KEY: $(REACT_APP_GOOGLE_API_KEY)
        REACT_APP_BASE_URL_ASSET: $(REACT_APP_BASE_URL_ASSET)
        REACT_APP_BASE_URL_ASSET_TOKEN: $(REACT_APP_BASE_URL_ASSET_TOKEN)
        REACT_APP_DUMMY_EMAIL: $(REACT_APP_DUMMY_EMAIL)
        REACT_APP_DUMMY_PASSWORD: $(REACT_APP_DUMMY_PASSWORD)
        REACT_APP_BASE_URL_CA: $(REACT_APP_BASE_URL_CA)
