parameters:
  - name: deploymentToken
    type: string

jobs:
- job: Deploy
  displayName: "Deploy Azure Static Web App"
  steps:

    - checkout: self

    # 🔍 DEBUG — VERIFY TOKEN IS ACTUALLY PRESENT
    - script: |
        echo "=============================="
        echo "Checking deployment token..."
        echo "Token length: ${#TOKEN}"
        echo "=============================="
      displayName: "DEBUG: Verify Deployment Token"
      env:
        TOKEN: ${{ parameters.deploymentToken }}

    # (Optional) Build step — adjust if needed
    - script: |
        npm install
        npm run build
      displayName: "Build Application"

    # 🚀 Static Web App Deploy
    - task: AzureStaticWebApp@0
      displayName: "Deploy to Azure Static Web App"
      inputs:
        app_location: "/"
        output_location: "dist"   # change if your build output is different
        azure_static_web_apps_api_token: ${{ parameters.deploymentToken }}
