parameters:
  - name: deploymentToken
    type: string

jobs:
- job: Deploy
  displayName: "Deploy Azure Static Web App"
  steps:

    - checkout: self
    # 🚀 Static Web App Deploy
    - task: AzureStaticWebApp@0
      displayName: "Deploy to Azure Static Web App"
      inputs:
        app_location: "/"          # root of app
        output_location: "dist"    # change if build output differs
        azure_static_web_apps_api_token: ${{ parameters.deploymentToken }}
