parameters:
  - name: deploymentToken
    type: string

jobs:
- job: Deploy
  displayName: "Deploy Static Web App"
  steps:
    - task: AzureStaticWebApp@0
      inputs:
        app_location: "/"
        output_location: "dist"
        azure_static_web_apps_api_token: ${{ parameters.deploymentToken }}
