# Quality + Sonar combined template
parameters:
  - name: sonarenabled
    type: boolean
    default: true

jobs:
- job: Quality_And_Sonar
  displayName: "Quality Check + Sonar Analysis"
  steps:

  # Extract version from package.json
  - bash: |
      echo "##vso[task.setvariable variable=PROJECT_VERSION]$(cat ./package.json | jq -r .version)"
    displayName: "Extract Project Version"

  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: '20.15.0'

  - script: |
      npm install
      npm run test
    displayName: "Run Unit Tests"
    env:
      NODE_OPTIONS: "--max-old-space-size=8192"
      ENCRYPTION_KEY: $(ENCRYPTION_KEY)

  - task: PublishCodeCoverageResults@2
    displayName: "Publish Code Coverage"
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'coverage/clover.xml'

  # ---------- CONDITIONAL SONAR ----------
  - ${{ if eq(parameters.sonarenabled, true) }}:
    - template: sonar.yml
