# Quality + Sonar combined Template
parameters:
  - name: sonarenabled
    type: boolean
    default: true

jobs:
- job: Quality_And_Sonar
  displayName: "Quality Check + Sonar Analysis"

  steps:

  - bash: echo "##vso[task.setvariable variable=PROJECT_VERSION]$(cat ./package.json | jq -r .version)"
    displayName: "Extract version from package.json"

  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: '20.11.1'

  - script: |
      npm install
      npm run test
    env:
      ENCRYPTION_KEY: $(ENCRYPTION_KEY)
    displayName: "Run Unit Tests"

  - task: PublishCodeCoverageResults@2
    displayName: "Publish Code Coverage"
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'coverage/clover.xml'

  # Sonar Steps
  - ${{ if eq(parameters.sonarenabled, true) }}:
    - template: sonar.yml
