export interface EmissionSavedState {
    isError: any,
    isSuccess: boolean,
    isLoading: boolean,
    message: string,
    isLoadingFilters: boolean,
    emissionSavedFilters: any,
    emissionSavedScacs: any,
    isLoadingScacList: boolean,
    emissionSavedMatricsData: any,
    isLoadingEmissionMatricsData: boolean,
    emissionSavedShipmentGraphData: any,
    isLoadingEmissionSavedShipmentGraph: boolean,
    emissionSavedEmissionGraphData: any,
    isLoadingEmissionSavedEmissionGraph: boolean,
    emissionSavedTransactionTableData: any,
    isLoadingEmissionSavedTransactionTable: boolean,
    emissionSavedFuelType: any,
    isLoadingEmissionSavedFuelType: boolean,
};